name: CI workflow
on:
  push

jobs:
  run-linter-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: npm install
        run: npm i

      - name: Lint code
        run: npm run lint:staged

      - name: Run tests
        run: npm test